import {
  Activity,
  AlertCircle,
  Archive,
  AtSign,
  BarChart3,
  Battery,
  Bell,
  Bird,
  Bluetooth,
  Box,
  Brush,
  Bug,
  Calendar,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Clock,
  Columns,
  Compass,
  Cpu,
  Database,
  Download,
  Droplets,
  ExternalLink,
  Eye,
  EyeOff,
  FileJson,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  Flame,
  Folder,
  Gift,
  Ghost,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Heart,
  Home,
  Image,
  Info,
  Key,
  Languages,
  Layout,
  Leaf,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Monitor,
  Moon,
  Mountain,
  MousePointer2,
  MoveRight,
  Palette,
  Pause,
  Phone,
  PieChart,
  Play,
  Plus,
  Power,
  Radio,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  Shapes,
  Share,
  Shield,
  ShieldCheck,
  Smile,
  Smartphone,
  Sparkles,
  Sprout,
  SquareStack,
  Star,
  Sun,
  Table,
  Terminal,
  Trash,
  Trash2,
  TreePine,
  Trees,
  Layers,
  Unlock,
  User,
  Users,
  Waves,
  Wifi,
  Wind,
  Zap,
} from 'lucide-react';
import type { IconCategory, IconItem, NavTab } from './types';

export const tokens = {
  colors: {
    brand: {
      amber: '#FFCA3A',
      rose: '#FF595E',
      azure: '#1982C4',
      lime: '#8AC926',
    },
    states: {
      positive: '#8AC926',
      warning: '#FFCA3A',
      danger: '#FF595E',
      info: '#1982C4',
    },
    ambient: {
      light: { nav: '#EDEBE3', content: '#F7F3F3', border: '#CED6DF' },
      dark: {
        nav: '#0B0E14',
        content: '#0B0E14',
        surface: '#141A24',
        border: '#232D3D',
      },
    },
  },
  typography: {
    families: {
      display: 'font-serif',
      body: 'font-sans',
    },
  },
  spacing: [
    { name: '4xs', value: '2px' },
    { name: 'xs', value: '4px' },
    { name: 'sm', value: '8px' },
    { name: 'md', value: '16px' },
    { name: 'lg', value: '24px' },
    { name: 'xl', value: '32px' },
    { name: '2xl', value: '48px' },
    { name: '3xl', value: '64px' },
  ],
  radius: 'rounded-[2rem] rounded-tr-md rounded-bl-md',
} as const;

export const navTabs: NavTab[] = [
  { id: 'manifesto', label: 'Manifesto', icon: Compass, color: tokens.colors.brand.lime },
  { id: 'foundations', label: 'Foundations', icon: Palette, color: tokens.colors.brand.rose },
  { id: 'architecture', label: 'Architecture', icon: Layout, color: tokens.colors.brand.amber },
  { id: 'components', label: 'Components', icon: Box, color: tokens.colors.brand.azure },
  { id: 'icons', label: 'Icon Library', icon: Shapes, color: tokens.colors.brand.lime },
  { id: 'decorative', label: 'Signature', icon: Brush, color: tokens.colors.brand.rose },
];

export const iconLibrary: Record<IconCategory, IconItem[]> = {
  botanical: [
    { name: 'Leaf', icon: Leaf }, { name: 'Wind', icon: Wind }, { name: 'Sparkles', icon: Sparkles }, { name: 'Zap', icon: Zap }, { name: 'Shapes', icon: Shapes }, { name: 'Brush', icon: Brush }, { name: 'Cloud', icon: Cloud }, { name: 'Sun', icon: Sun }, { name: 'Moon', icon: Moon }, { name: 'Sprout', icon: Sprout }, { name: 'Trees', icon: Trees }, { name: 'TreePine', icon: TreePine }, { name: 'Droplets', icon: Droplets }, { name: 'Flame', icon: Flame }, { name: 'Mountain', icon: Mountain }, { name: 'Waves', icon: Waves }, { name: 'Bird', icon: Bird }, { name: 'Bug', icon: Bug }, { name: 'Ghost', icon: Ghost }, { name: 'Camera', icon: Camera },
  ],
  action: [
    { name: 'MoveRight', icon: MoveRight }, { name: 'Maximize2', icon: Maximize2 }, { name: 'MousePointer2', icon: MousePointer2 }, { name: 'Plus', icon: Plus }, { name: 'Trash', icon: Trash }, { name: 'Trash2', icon: Trash2 }, { name: 'Download', icon: Download }, { name: 'Share', icon: Share }, { name: 'RotateCcw', icon: RotateCcw }, { name: 'ChevronRight', icon: ChevronRight }, { name: 'ChevronLeft', icon: ChevronLeft }, { name: 'ChevronDown', icon: ChevronDown }, { name: 'ExternalLink', icon: ExternalLink }, { name: 'Eye', icon: Eye }, { name: 'EyeOff', icon: EyeOff }, { name: 'Filter', icon: Filter }, { name: 'Play', icon: Play }, { name: 'Pause', icon: Pause }, { name: 'RefreshCw', icon: RefreshCw }, { name: 'Send', icon: Send },
  ],
  communication: [
    { name: 'Mail', icon: Mail }, { name: 'Phone', icon: Phone }, { name: 'MapPin', icon: MapPin }, { name: 'MessageSquare', icon: MessageSquare }, { name: 'MessageCircle', icon: MessageCircle }, { name: 'Bell', icon: Bell }, { name: 'Flag', icon: Flag }, { name: 'User', icon: User }, { name: 'Users', icon: Users }, { name: 'Heart', icon: Heart }, { name: 'Star', icon: Star }, { name: 'Globe', icon: Globe }, { name: 'AtSign', icon: AtSign }, { name: 'Link', icon: Link }, { name: 'Gift', icon: Gift }, { name: 'Smile', icon: Smile }, { name: 'Languages', icon: Languages }, { name: 'Hash', icon: Hash }, { name: 'Megaphone', icon: Megaphone }, { name: 'Radio', icon: Radio },
  ],
  system: [
    { name: 'Settings', icon: Settings }, { name: 'Search', icon: Search }, { name: 'Info', icon: Info }, { name: 'AlertCircle', icon: AlertCircle }, { name: 'CheckCircle2', icon: CheckCircle2 }, { name: 'Lock', icon: Lock }, { name: 'Unlock', icon: Unlock }, { name: 'Fingerprint', icon: Fingerprint }, { name: 'Home', icon: Home }, { name: 'Activity', icon: Activity }, { name: 'Clock', icon: Clock }, { name: 'Calendar', icon: Calendar }, { name: 'Key', icon: Key }, { name: 'Shield', icon: Shield }, { name: 'ShieldCheck', icon: ShieldCheck }, { name: 'Terminal', icon: Terminal }, { name: 'Power', icon: Power }, { name: 'Bluetooth', icon: Bluetooth }, { name: 'Wifi', icon: Wifi }, { name: 'Map', icon: Map },
  ],
  data: [
    { name: 'SquareStack', icon: SquareStack }, { name: 'Layers', icon: Layers }, { name: 'Columns', icon: Columns }, { name: 'Layout', icon: Layout }, { name: 'Database', icon: Database }, { name: 'Monitor', icon: Monitor }, { name: 'Smartphone', icon: Smartphone }, { name: 'Image', icon: Image }, { name: 'FileText', icon: FileText }, { name: 'Battery', icon: Battery }, { name: 'HardDrive', icon: HardDrive }, { name: 'Cpu', icon: Cpu }, { name: 'BarChart3', icon: BarChart3 }, { name: 'PieChart', icon: PieChart }, { name: 'Table', icon: Table }, { name: 'FileJson', icon: FileJson }, { name: 'Folder', icon: Folder }, { name: 'Archive', icon: Archive }, { name: 'Grid', icon: Grid }, { name: 'List', icon: List },
  ],
};

export const typographyPulse = [
  { label: 'Display / Serif', size: 'text-7xl', weight: 'font-normal', font: 'font-serif' },
  { label: 'Heading / Serif', size: 'text-4xl', weight: 'font-bold', font: 'font-serif' },
  { label: 'Body / Inter', size: 'text-lg', weight: 'font-medium', font: 'font-sans' },
  { label: 'Label / Inter', size: 'text-[10px]', weight: 'font-black', font: 'font-sans' },
] as const;

export const breakpoints = ['SM: 640px', 'MD: 768px', 'LG: 1024px', 'XL: 1280px'] as const;
